# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPhtDy8qw3zVOrqQ9Fy8EPrmRSVGfX6b
"""

!pip install "langchain==0.3.25" "langchain-community==0.3.24" "langchain-text-splitters==0.3.8" "langchain-google-genai==2.1.5" faiss-cpu sentence-transformers pypdf -q

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

from google.colab import drive
drive.mount('/content/drive')

import os
from langchain_community.document_loaders import DirectoryLoader, TextLoader, PyPDFLoader

DATA_PATH = "/content/drive/MyDrive/my_personal_data"
os.makedirs(DATA_PATH, exist_ok=True)  # creates the folder if it doesn't exist yet

documents = []
documents += DirectoryLoader(DATA_PATH, glob="**/*.txt", loader_cls=TextLoader).load()
documents += DirectoryLoader(DATA_PATH, glob="**/*.pdf", loader_cls=PyPDFLoader).load()

print(f"Loaded {len(documents)} documents")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
chunks = splitter.split_documents(documents)
print(f"Split into {len(chunks)} chunks")

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectorstore = FAISS.from_documents(chunks, embeddings)
vectorstore.save_local("/content/drive/MyDrive/my_rag_index")
print("Vector store saved.")

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate

llm = ChatGoogleGenerativeAI(model="gemini-3.6-flash", temperature=0.3)

prompt_template = """You are a helpful assistant that answers questions using only the context below, which is personal information about the user. If the answer isn't in the context, say you don't know — don't make things up.

Context:
{context}

Question: {question}
Answer:"""

prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type_kwargs={"prompt": prompt}
)

response = qa_chain.invoke({"query": "what is aI"})
print(response["result"])